GET http://localhost:6700/exercises/all
Content-Type: application/json
Authorization: Bearer 6478a18d3d81a36185d39967e74d265153c8c381fc8db0d32ade445cc31a2c59

###

GET http://localhost:6700/mydata
Content-Type: application/json
Authorization: Bearer 6478a18d3d81a36185d39967e74d265153c8c381fc8db0d32ade445cc31a2c59

###

POST http://localhost:6700/auth/register
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "password"
}

###

POST http://localhost:6700/auth/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "password"
}